Repository game-of-nfts/gon-evidence, pull requests merged in 2023-03, with the labels that each got.

#204 Evidence Submission for TC Network
  trulacgc-tcnetwork/evidence.xlsx
Labels: stage-1

#285 evidence and task A1-A6
  goooodnes/evidence.xlsx
Labels: stage-1

#294 Update evidence for task A1-A6
  imnisen/evidence.xlsx
Labels: stage-1

#340 Update evidence A1-A6 (Stage 1)
  wetezos/evidence.xlsx
Labels: stage-1

#339 Add evidence for stage-1 (A1-A6)
  EkonnK/evidence.xlsx
Labels: stage-1

#327 stage1 evidence
  ZhihangLiu2020/evidence.xlsx
Labels: stage-1

#326 Add evidence for A1-A6 tasks (stage-1)
  ilkeff/evidence.xlsx
Labels: stage-1

#324 upload evidences for stage-1
  onurhizlan/evidence.xlsx
Labels: stage-1

#325 feat: A1 to A6 tasks evidences
  0xtekgrinder/evidence.xlsx
Labels: stage-1

#321 Add Stage 1 Tasks (A1-A6)
  ciprianmuja/evidence.xlsx
Labels: stage-1

#320 upload evidence for stage-1 (A1-A6)
  szryldrm/evidence.xlsx
Labels: stage-1

#318 Added evidences (A1-A6)
  tiramisu26/evidence.xlsx
Labels: stage-1

#319 Add evidence for stage-1
  sarsersirsur/evidence.xlsx
Labels: stage-1

#317 evidence (A1-A6) for Stage-1
  cjisthecat/evidence.xlsx
Labels: stage-1

#316 Complete tasks of stage 1
  LiangLiang918/evidence.xlsx
Labels: stage-1

#315 Stage A1-A6
  kadiralan/evidence.xlsx
Labels: stage-1

#314 busteter added A1-A6
  busteter/evidence.xlsx
Labels: stage-1

#312 Update evidence for task (A1-A6)
  selimkafa/evidence.xlsx
Labels: stage-1

#310 Update evidences for A1-A6
  timveltman3/evidence.xlsx
Labels: stage-1

#309 Stage-1 Tasks A1-A6
  blasmorkai/evidence.xlsx
Labels: stage-1

#307 ibrahimdulger A1-A6 added
  ibrahimdulger/evidence.xlsx
Labels: stage-1

#303 Update evidence for task A1-A6
  karat0/evidence.xlsx
Labels: stage-1

#300 Stage-1 Evidence A1-A6
  techwomen35/evidence.xlsx
Labels: stage-1

#297 add evidence for A1-A6 (stage-1)
  kanakattack/evidence.xlsx
Labels: stage-1

#296 Update evidence for task A1-A6
  gokmenkutuk/evidence.xlsx
Labels: stage-1

#292 Update evidence for task A1-A6
  okannako/evidence.xlsx
Labels: stage-1

#291 Update evidence for task A1-A6
  kivancbeser/evidence.xlsx
Labels: stage-1

#290 Update evidence for task A1-A6
  arnettee/evidence.xlsx
Labels: stage-1

#288 Update evidence for task A1-A6
  DasRasyo/evidence.xlsx
Labels: stage-1

#286 stguller2 stage-1 A1 to A6 evidence
  stguller2/evidence.xlsx
Labels: stage-1

#287 adds evidences bw A1-A6
  mcanvar/evidence.xlsx
Labels: stage-1

#289 Add evidence A1-A6
  nurtagum/evidence.xlsx
Labels: stage-1

#284 Update evidence for task A1-A6
  chainsmt/evidence.xlsx
Labels: stage-1

#283 Update evidence for task A1-A6
  farukyasar/evidence.xlsx
Labels: stage-1

#280 update evidence for task A1-A6
  superdreams/evidence.xlsx
Labels: stage-1

#278 Update evidence for task A1-A6
  ben-razor/evidence.xlsx
Labels: stage-1

#279 Evidence for tasks A1-A6
  IAmScRay/evidence.xlsx
Labels: stage-1

#276 stage1 task a1-6
  alipostaci2001/evidence.xlsx
Labels: stage-1

#271 okwme Step 1 PR
  okwme/evidence.xlsx
Labels: stage-1

#269 update evidence for task A1-A6
  songjiazhun/evidence.xlsx
Labels: stage-1

#272 evidence for task A1-A6
  liwenjia345/evidence.xlsx
Labels: stage-1

#273 update evidence for task A1-A6
  R-Future/evidence.xlsx
Labels: stage-1

#274 Tasks：A1, A2, A3, A4, A5, A6
  vivensy/evidence.xlsx
Labels: stage-1

#268 update evidence for task A1-A6
  remianch/evidence.xlsx
Labels: stage-1

#265 Stage-1 Tasks A1-A6
  Vgk88/evidence.xlsx
Labels: stage-1

#264 Stage-1 Tasks A1-A6
  oOZz/evidence.xlsx
Labels: stage-1

#262 Stage-1 Tasks A1-A6
  alpe/evidence.xlsx
Labels: stage-1

#263 Stage-1
  pinosu/evidence.xlsx
Labels: stage-1

#261 stage1 A1-A6 and stage2 A7~A20
  BCSungjin/evidence.xlsx
Labels: stage-1, stage-2

#260 stage 1 a1-a6
  N1ghtSe7en/evidence.xlsx
Labels: stage-1

#254 Update moodman evidence.xlsx for Task A1-A6
  Boblev999/evidence.xlsx
Labels: stage-1

#256 Kalia Network - Adding Stage 1 Evidence for A1-A2-A3-A4-A5-A6
  KaliaNetwork/evidence.xlsx
Labels: stage-1

#257 dankuzone /w DAIC - evidence submission for tasks A1-A6
  DAICers/evidence.xlsx
Labels: stage-1

#259 osmanbo stage-1 A1 to A6 evidence
  osmanbo/evidence.xlsx
Labels: stage-1

#252 Task A1-A6
  studentmtk/evidence.xlsx
Labels: stage-1

#251 Update evidence for Task A1-A6
  VasyaIvanov21/evidence.xlsx
Labels: stage-1

#250 landeros Task A1-A6
  landerosua/evidence.xlsx
Labels: stage-1

#249 A1-A6 completed
  79anvi/evidence.xlsx
Labels: stage-1

#242 Meerlabs completed tasks A1-A20
  Caneryy/evidence.xlsx
Labels: stage-1, stage-2

#243 Stage-1 Tasks A1-A6
  ptts55/evidence.xlsx
Labels: stage-1

#244 Stage-1 Tasks A1-A6
  IvVasil/evidence.xlsx
Labels: stage-1

#247 Update Lefey evidence.xlsx A1-A6
  Lefey/evidence.xlsx
Labels: stage-1

#248 cyberomanov: A1-A6 done.
  cyberomanov/evidence.xlsx
Labels: stage-1

#240 Moonlet stage 1 evidence
  krisboit/evidence.xlsx
Labels: stage-1

#234 Completed Stage 1 Tasks
  hexp1989/evidence.xlsx
Labels: stage-1

#241 Commercio.Network stage-1
  marcotradenet/evidence.xlsx
Labels: stage-1

#232 add stage 1 evidence from xavier
  xavier200203/evidence.xlsx
Labels: stage-1

#219 DSRV: Update evidence for Task A1-A20
  heejin-github/evidence.xlsx
Labels: stage-1, stage-2

#218 Stage 1: Tasks: A1, A2, A3, A4, A5, A6
  gruberx/evidence.xlsx
Labels: stage-1

#217 #decentralizehk - DHK dao Team evidence A1-A6
  dhkgon/evidence.xlsx
Labels: stage-1

#226 Add phase1 task evidence
  kaizhizhang/evidence.xlsx
Labels: stage-1

#228 Added in tasks 1
  JianHongHong/evidence.xlsx
Labels: stage-1

#213 chillyvee Evidence A1-A6
  chillyvee/evidence.xlsx
Labels: stage-1

#215 yekssin evidence A1-A6
  yekssin/evidence.xlsx
Labels: stage-1

#214 Oldcat Evidence A1-A6
  oldcatv/evidence.xlsx
Labels: stage-1, stage-2

#216 alkadeta evidence A1-A6
  alkadeta/evidence.xlsx
Labels: stage-1

#200 A1-A6 for gjermundgaraba/empowerchain
  gjermundgaraba/evidence.xlsx
Labels: stage-1

#202 NodeStake Task A1-A6
  nodestake/evidence.xlsx
Labels: stage-1

#203 Adding Evidence beal2912 A1-A6
  beal2912/evidence.xlsx
Labels: stage-1

#207 Disperze Tasks A1-A6
  giansalex/evidence.xlsx
Labels: stage-1

#195 Taskn A1-A6
   Wangxiaolei123456/evidence.xlsx
Labels: stage-1

#199 UniqLabs A1-A6 tasks + A7-A20 tasks
  uniqlabsorg/evidence.xlsx
Labels: stage-1

#135 Update evidences for phase 1
  joshlopes/evidence.xlsx
Labels: stage-1

#141 Evidence for A1-A6
  taitruong/evidence.xlsx
Labels: stage-1

#156 Update Phase 1 (A1-A6) and Phase 2 (A7-A20) evidence.
  nodeiistt/evidence.xlsx
Labels: stage-1, stage-2

#150 add stage 1 evidence
  si35/evidence.xlsx
Labels: stage-1

#159 Update Phase 1 (A1-A6) and Phase 2 (A7~A20) evidence
  omercanyenigun/evidence.xlsx
Labels: stage-1, stage-2

#189 A1-A2-A3-A4-A5-A6 Task Update
  secard51/evidence.xlsx
Labels: stage-1

#187 Evidence Task A1-A6
  arifintahu/evidence.xlsx
Labels: stage-1

#183 finish A1-A20
  williamqiao/evidence.xlsx
Labels: stage-1, stage-2

#185 Submit A1-A6 task
  ElfenLied2019/evidence.xlsx
Labels: stage-1

#186 Add nkbblocks stage1 A1 to A6 evidence
  anurg/evidence.xlsx
Labels: stage-1

#182 finish task A1-A6
  gouzhiyuan/evidence.xlsx
Labels: stage-1

#180 Tasks：A1, A2, A3, A4, A5, A6
  TheCodeor /evidence.xlsx
Labels: stage-1

#175 commit Task A1~A6
  ShenFri/evidence.xlsx
Labels: stage-1

#181 Update evidence.xlsx
  zhangweidong123/evidence.xlsx
Labels: stage-1

#172 update A1-6 evidence
  dolphintwo/evidence.xlsx
Labels: stage-1

#169 Update evidence A1-6
  Exclusive048/evidence.xlsx
Labels: stage-1

#164 evidence
  elfelf2/evidence.xlsx
Labels: stage-1

#124 add williamchong (Liker Land) A1-A6 evidence
  williamchong/evidence.xlsx
Labels: stage-1

#337 Registration evidence
  0xMemoryGrinder/evidence.xlsx
Labels: stage-1

#225 Cypher Core - Add Evidence for Task A1-A6
  jim380/evidence.xlsx
Labels: stage-1

#349 Stage 1 & 2 evidence
  gokceeee/evidence.xlsx
Labels: stage-1, stage-2

#367 Add evidence for A1-A20 tasks (stage-1,2)
  furkanefe-oss/evidence.xlsx
Labels: stage-1, stage-2

#364 Add evidence for A1-A6 tasks (stage-1)
  ibrahimarslann59/evidence.xlsx
Labels: stage-1, stage-2

#363 Tasks A1-A20
  allyter/evidence.xlsx
Labels: stage-1, stage-2

#362 osmanbo stage-2 add A7 to A20
  osmanbo/evidence.xlsx
Labels: stage-1, stage-2

#373 Stage 2 A7-A20
  vivensy/evidence.xlsx
Labels: stage-2

#358 2019jack stage2 add A7 to A20
  2019jack/evidence.xlsx
Labels: stage-2

#385 Fix Sheet Format for Cypher Core
  jim380/evidence.xlsx
Labels: stage-1

#415 Task A7-A20 + format fix
  gjermundgaraba/evidence.xlsx
Labels: stage-2

#414 Update evidence for task A1-A6
  trulacgc-tcnetwork/evidence.xlsx
Labels: stage-1

#237 Add Kleomedes and completed tasks A1-A6
  kleomedes/evidence.xlsx
  template/evidence.xlsx
Labels: stage-1

#211 BlockHunters evidence Tasks A1-A6 + folder name change as requested
  blockhunters-dev/evidence.xlsx
Labels: stage-1

#387 Fixed - evidence format error
  Boblev999/evidence.xlsx
Labels: stage-1

#388 fix: (evidence format error): task evidence format is incorrect
  williamqiao/evidence.xlsx
Labels: stage-1

#389 update evidence format (A1-A6)
  ibrahimarslann59/evidence.xlsx
Labels: stage-1

#390 Update with correct wasm prefix A3, A5
  uniqlabsorg/evidence.xlsx
Labels: stage-1

#391 Update evidence format error
  BCSungjin/evidence.xlsx
Labels: stage-1

#400 Update evidence correct classID for A3, A5
  furkanefe-oss/evidence.xlsx
Labels: stage-1

#405 updated a mistype of chain-ID in A3
  oldcatv/evidence.xlsx
Labels: stage-1

#410 Update Evidence Format (STAGE 1)
  deden2904/evidence.xlsx
Labels: stage-1

#417 Fix Stage 1 Evidence Format - chillyvee
  chillyvee/evidence.xlsx
Labels: stage-1

#399 Fixed template issue
  omercanyenigun/evidence.xlsx
Labels: stage-1

#398 Moonlet update evidence Stage 1 (A1 - A6)
  krisboit/evidence.xlsx
Labels: stage-1

#396 update evidence format (A1-A6)
  DasRasyo/evidence.xlsx
Labels: stage-1

#392 fix williamchong (Liker Land) phase 1 formatting
  williamchong/evidence.xlsx
Labels: stage-1

#386 A1-A20 update corrected the wasm prefix at a3 task
  mahofmahof/evidence.xlsx
Labels: stage-1

#380 Fixed stage 1 evidence file format
  si35/evidence.xlsx
Labels: stage-1

#382 Update evidence for Task A1-A6
  landerosua/evidence.xlsx
Labels: stage-1

#377 Update evidence format error task A1-A6 (Stage 1)
  DionGantung/evidence.xlsx
Labels: stage-1

#355 fixed revisit evidence b1-4
  nodeiistt/evidence.xlsx
Labels: stage-2

#357 Stage2: ShenFri add A7 to A20
  ShenFri/evidence.xlsx
Labels: stage-2

#360 A7~A20
  HashQuark-Research1/evidence.xlsx
Labels: stage-2

#375 update 2019jack stage2 A19、A20 tx hash
  2019jack/evidence.xlsx
Labels: stage-2

#379 Fix classID for A3,A5. Was fix format of answers A7-A20
  Exclusive048/evidence.xlsx
Labels: stage-2

#374 stguller2 Solved format error Stage 1 and Stage 2 (A1-A20)
  stguller2/evidence.xlsx
Labels: stage-2

#383 update dolphintwo A7-20 evidence
  dolphintwo/evidence.xlsx
Labels: stage-2

#384 Stage2 - #decentralizehk - DHK DAO Team add A7-A20, fix typo A2, A4
  dhkgon/evidence.xlsx
Labels: stage-2

#394 Disperze stage-1, stage-2
  giansalex/evidence.xlsx
Labels: stage-2

#395 Stage1 format error fix and Stage2 evidences
  EmreNOP/evidence.xlsx
Labels: stage-2

#402 Evidence stage 2 ~ A7-A20 and update A3, A5 classID
  arifintahu/evidence.xlsx
Labels: stage-2

#407 marcotradenet for Commercio.Network A7-A20 stage-2
  marcotradenet/evidence.xlsx
Labels: stage-2

#409 add williamchong (Liker Land) A7-A20 evidence
  williamchong/evidence.xlsx
Labels: stage-2

#416 stage2 A7-A20 - alipostaci2001
  alipostaci2001/evidence.xlsx
Labels: stage-2

#418 Solved format error Stage 1 and Stage 2 Up A1-A20
  secard51/evidence.xlsx
Labels: stage-2

#419 beal2912 - A1-A6 format correction + evidence for A7-A20
  beal2912/evidence.xlsx
Labels: stage-2

#422 feat: add evidences of stage 2
  0xtekgrinder/evidence.xlsx
Labels: stage-2

#424 Add phase 2 evidence
  kaizhizhang/evidence.xlsx
Labels: stage-2

#342 Stage2: chillyvee add a7 to a20
  chillyvee/evidence.xlsx
Labels: stage-2
